name: Pypi

on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    if: github.actor == 'miigotu'
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Restore pip cache
        uses: actions/cache@v2
        with:
          path: $(python -m pip cache dir)
          key: ${{ runner.os }}-pip-${{ hashFiles('sickchill/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel twine tox build
      - name: Checkout SickChill
        uses: actions/checkout@v2
        with:
          ref: master
          path: sickchill
          fetch-depth: 0
      - name: Publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        working-directory: sickchill
        run: |
          git config --global user.name miigotu
          git config --global user.email miigotu@gmail.com
          git checkout master
          git reset --hard origin/develop
          python setup.py sdist bdist_wheel
          VERSION=$(grep -oP '\d+\.\d+\.\d+\.post\d+[^"]*' sickchill/version.py)
          git commit -asm "Release $VERSION"
          git tag $VERSION
          echo git push origin master
          git checkout develop
          git reset --hard master
          echo git push origin develop
          echo "Version is $VERSION"
          echo "twine upload dist/*"
